
CREATE DATABASE IF NOT EXISTS sistema_clinico;
USE sistema_clinico;

-- Tabela: D_USUARIO_PERFIL
CREATE TABLE D_USUARIO_PERFIL (
    ID_USUARIO_PERFIL INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_PERFIL_TIPO VARCHAR(255),
    USUARIO_PERFIL_CRIACAO DATETIME,
    USUARIO_PERFIL_ATUALIZACAO DATETIME
);

-- Tabela: D_SISTEMA
CREATE TABLE D_SISTEMA (
    ID_SISTEMA INT PRIMARY KEY AUTO_INCREMENT,
    SISTEMA_NOME VARCHAR(255),
    SISTEMA_VERSAO VARCHAR(255),
    SISTEMA_DESC VARCHAR(255),
    SISTEMA_DATA_CRIACAO DATETIME,
    SISTEMA_DATA_ATUALIZACAO DATETIME,
    SISTEMA_DESENVOLVEDOR VARCHAR(255)
);

-- Tabela: D_CLINICA
CREATE TABLE D_CLINICA (
    ID_CLINICA INT PRIMARY KEY AUTO_INCREMENT,
    CLINICA_NOME VARCHAR(255),
    CLINICA_DESC VARCHAR(255),
    CLINICA_TELEFONE VARCHAR(255),
    CLINICA_ESTADO VARCHAR(255),
    CLINICA_MUNICIPIO VARCHAR(255),
    CLINICA_BAIRRO VARCHAR(255),
    CLINICA_ENDERECO VARCHAR(255),
    CLINICA_NUMERO VARCHAR(255),
    CLINICA_CEP VARCHAR(255),
    CLINICA_END_COMPLEMENTO VARCHAR(255),
    CLINICA_DATA_CRIACAO DATETIME,
    CLINICA_DATA_ATUALIZACAO DATETIME
);

-- Tabela: F_USUARIO
CREATE TABLE F_USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_NOME VARCHAR(255),
    USUARIO_EMAIL VARCHAR(255),
    USUARIO_CPF VARCHAR(11),
    USUARIO_GENERO VARCHAR(255),
    USUARIO_SENHA VARCHAR(255),
    USUARIO_DATA_CRIACAO DATETIME,
    USUARIO_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID_USUARIO_PERFIL INT,
    F_USUARIO_ID_CLINICA INT,
    D_SISTEMA_ID INT,
    FOREIGN KEY (F_USUARIO_ID_USUARIO_PERFIL) REFERENCES D_USUARIO_PERFIL(ID_USUARIO_PERFIL),
    FOREIGN KEY (F_USUARIO_ID_CLINICA) REFERENCES D_CLINICA(ID_CLINICA),
    FOREIGN KEY (D_SISTEMA_ID) REFERENCES D_SISTEMA(ID_SISTEMA)
);

-- Tabela: D_ENDERECO
CREATE TABLE D_ENDERECO (
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    ENDERECO_END_LOGRADOURO VARCHAR(255),
    ENDERECO_END_NUMERO VARCHAR(255),
    ENDERECO_END_COMPLEMENTO VARCHAR(255),
    ENDERECO_END_BAIRRO VARCHAR(255),
    ENDERECO_END_CEP VARCHAR(255),
    ENDERECO_END_CIDADE VARCHAR(255),
    ENDERECO_END_ESTADO VARCHAR(255),
    ENDERECO_DATA_CRIACAO DATETIME,
    ENDERECO_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID INT,
    F_USUARIO_ID_CLINICA INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO),
    FOREIGN KEY (F_USUARIO_ID_CLINICA) REFERENCES D_CLINICA(ID_CLINICA)
);

-- Tabela: D_NOTIFICACAO
CREATE TABLE D_NOTIFICACAO (
    ID_NOTIFICACAO INT PRIMARY KEY AUTO_INCREMENT,
    NOTIFICACAO_TITULO VARCHAR(255),
    NOTIFICACAO_ASSUNTO LONGTEXT,
    NOTIFICACAO_MENSAGEM VARCHAR(255),
    NOTIFICACAO_REMETENTE VARCHAR(255),
    NOTIFICACAO_DESTINATARIO VARCHAR(255),
    NOTIFICACAO_DATA_CRIACAO DATETIME,
    NOTIFICACAO_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO)
);

-- Tabela: D_REABILITACAO
CREATE TABLE D_REABILITACAO (
    ID_REABILITACAO INT PRIMARY KEY AUTO_INCREMENT,
    REABILITACAO_NOME VARCHAR(255),
    REABILITACAO_DESC LONGTEXT,
    REABILITACAO_MOMENTO VARCHAR(255),
    REABILITACAO_DESC_MOMENTO LONGTEXT,
    REABILITACAO_ORDEM VARCHAR(255),
    REABILITACAO_DATA_CRIACAO DATETIME,
    REABILITACAO_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO)
);

-- Tabela: D_QUESTIONARIO
CREATE TABLE D_QUESTIONARIO (
    ID_QUESTIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    QUESTIONARIO_TITULO VARCHAR(255),
    QUESTIONARIO_DESC VARCHAR(255),
    QUESTIONARIO_PERGUNTA LONGTEXT,
    QUESTIONARIO_NOTA VARCHAR(255),
    QUESTIONARIO_RESPOSTA VARCHAR(255),
    QUESTIONARIO_DATA_CRIACAO DATETIME,
    QUESTIONARIO_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO)
);

-- Tabela: D_CIRURGIA
CREATE TABLE D_CIRURGIA (
    ID_CIRURGIA INT PRIMARY KEY AUTO_INCREMENT,
    CIRURGIA_TIPO VARCHAR(255),
    CIRURGIA_DESC VARCHAR(255),
    CIRURGIA_OBSERVACAO VARCHAR(255),
    CIRURGIA_DATA_CRIACAO DATETIME,
    CIRURGIA_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO)
);

-- Tabela: D_MEDICO
CREATE TABLE D_MEDICO (
    ID_MEDICO INT PRIMARY KEY AUTO_INCREMENT,
    MEDICO_CRM VARCHAR(255),
    MEDICO_ESPECIALIDADE VARCHAR(255),
    F_USUARIO_ID INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO)
);

-- Inserts iniciais para perfis de usuário
INSERT INTO D_USUARIO_PERFIL (USUARIO_PERFIL_TIPO, USUARIO_PERFIL_CRIACAO)
VALUES
  ('Administrador', NOW()),
  ('Médico', NOW()),
  ('Paciente', NOW());