CREATE DATABASE IF NOT EXISTS sistema_clinico;
USE sistema_clinico;

-- Tabela: D_USUARIO_PERFIL
CREATE TABLE D_USUARIO_PERFIL (
    ID_USUARIO_PERFIL INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_PERFIL_TIPO VARCHAR(255),
    USUARIO_PERFIL_CRIACAO DATETIME,
    USUARIO_PERFIL_ATUALIZACAO DATETIME
);

-- Tabela: D_SISTEMA
CREATE TABLE D_SISTEMA (
    ID_SISTEMA INT PRIMARY KEY AUTO_INCREMENT,
    SISTEMA_NOME VARCHAR(255),
    SISTEMA_VERSAO VARCHAR(255),
    SISTEMA_DESC VARCHAR(255),
    SISTEMA_DATA_CRIACAO DATETIME,
    SISTEMA_DATA_ATUALIZACAO DATETIME,
    SISTEMA_DESENVOLVEDOR VARCHAR(255)
);

-- Tabela: D_CLINICA
CREATE TABLE D_CLINICA (
    ID_CLINICA INT PRIMARY KEY AUTO_INCREMENT,
    CLINICA_NOME VARCHAR(255),
    CLINICA_DESC VARCHAR(255),
    CLINICA_TELEFONE VARCHAR(255),
    CLINICA_ESTADO VARCHAR(255),
    CLINICA_MUNICIPIO VARCHAR(255),
    CLINICA_BAIRRO VARCHAR(255),
    CLINICA_ENDERECO VARCHAR(255),
    CLINICA_NUMERO VARCHAR(255),
    CLINICA_CEP VARCHAR(255),
    CLINICA_END_COMPLEMENTO VARCHAR(255),
    CLINICA_DATA_CRIACAO DATETIME,
    CLINICA_DATA_ATUALIZACAO DATETIME
);

-- Tabela: F_USUARIO
CREATE TABLE F_USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_NOME VARCHAR(255) NOT NULL,
    USUARIO_EMAIL VARCHAR(255) NOT NULL,
    USUARIO_CIRURGIA DATE,
    USUARIO_CPF VARCHAR(14) NOT NULL UNIQUE,
    USUARIO_GENERO VARCHAR(255),
    USUARIO_SENHA VARCHAR(255) NOT NULL,
    USUARIO_DATA_CRIACAO DATETIME NOT NULL,
    USUARIO_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID_USUARIO_PERFIL INT,
    F_USUARIO_ID_CLINICA INT,
    D_SISTEMA_ID INT,
    ID_REABILITACAO INT NULL,
    FOREIGN KEY (F_USUARIO_ID_USUARIO_PERFIL) REFERENCES D_USUARIO_PERFIL(ID_USUARIO_PERFIL),
    FOREIGN KEY (F_USUARIO_ID_CLINICA) REFERENCES D_CLINICA(ID_CLINICA),
    FOREIGN KEY (D_SISTEMA_ID) REFERENCES D_SISTEMA(ID_SISTEMA),
    FOREIGN KEY (ID_REABILITACAO) REFERENCES D_REABILITACAO(ID_REABILITACAO) ON DELETE SET NULL
);

-- Tabela: D_ENDERECO
CREATE TABLE D_ENDERECO (
    ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    ENDERECO_END_LOGRADOURO VARCHAR(255),
    ENDERECO_END_NUMERO VARCHAR(255),
    ENDERECO_END_COMPLEMENTO VARCHAR(255),
    ENDERECO_END_BAIRRO VARCHAR(255),
    ENDERECO_END_CEP VARCHAR(255),
    ENDERECO_END_CIDADE VARCHAR(255),
    ENDERECO_END_ESTADO VARCHAR(255),
    ENDERECO_DATA_CRIACAO DATETIME,
    ENDERECO_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID INT,
    F_USUARIO_ID_CLINICA INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO),
    FOREIGN KEY (F_USUARIO_ID_CLINICA) REFERENCES D_CLINICA(ID_CLINICA)
);

-- Tabela: D_NOTIFICACAO
CREATE TABLE D_NOTIFICACAO (
    ID_NOTIFICACAO INT PRIMARY KEY AUTO_INCREMENT,
    NOTIFICACAO_TITULO VARCHAR(255),
    NOTIFICACAO_ASSUNTO LONGTEXT,
    NOTIFICACAO_MENSAGEM VARCHAR(255),
    NOTIFICACAO_REMETENTE VARCHAR(255),
    NOTIFICACAO_DESTINATARIO VARCHAR(255),
    NOTIFICACAO_DATA_CRIACAO DATETIME,
    NOTIFICACAO_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO)
);

-- Tabela: D_REABILITACAO
CREATE TABLE D_REABILITACAO (
    ID_REABILITACAO INT PRIMARY KEY AUTO_INCREMENT,
    REABILITACAO_NOME VARCHAR(255),
    REABILITACAO_DESC LONGTEXT,
    REABILITACAO_MOMENTO VARCHAR(255),
    REABILITACAO_DESC_MOMENTO LONGTEXT,
    REABILITACAO_ORDEM VARCHAR(255),
    REABILITACAO_DATA_CRIACAO DATETIME,
    REABILITACAO_DATA_ATUALIZACAO DATETIME
);

-- Tabela: D_QUESTIONARIO
CREATE TABLE D_QUESTIONARIO (
    ID_QUESTIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    QUESTIONARIO_TITULO VARCHAR(255),
    QUESTIONARIO_DESC VARCHAR(255),
    QUESTIONARIO_PERGUNTA LONGTEXT,
    QUESTIONARIO_NOTA VARCHAR(255),
    QUESTIONARIO_RESPOSTA VARCHAR(255),
    QUESTIONARIO_DATA_CRIACAO DATETIME,
    QUESTIONARIO_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO)
);

-- Tabela: D_CIRURGIA
CREATE TABLE D_CIRURGIA (
    ID_CIRURGIA INT PRIMARY KEY AUTO_INCREMENT,
    CIRURGIA_TIPO VARCHAR(255),
    CIRURGIA_DESC VARCHAR(255),
    CIRURGIA_OBSERVACAO VARCHAR(255),
    CIRURGIA_DATA_CRIACAO DATETIME,
    CIRURGIA_DATA_ATUALIZACAO DATETIME,
    F_USUARIO_ID INT,
    FOREIGN KEY (F_USUARIO_ID) REFERENCES F_USUARIO(ID_USUARIO)
);

-- Inserts iniciais para perfis de usuário
INSERT INTO D_USUARIO_PERFIL (USUARIO_PERFIL_TIPO, USUARIO_PERFIL_CRIACAO)
VALUES
  ('Administrador', NOW()),
  ('Medico', NOW()),
  ('Paciente', NOW());

-- Usuários padrão para testes
INSERT INTO F_USUARIO (USUARIO_NOME, USUARIO_EMAIL, USUARIO_CIRURGIA, USUARIO_CPF, USUARIO_GENERO, USUARIO_SENHA, USUARIO_DATA_CRIACAO, F_USUARIO_ID_USUARIO_PERFIL)
VALUES
  ('Administrador', 'admin.GP25ads@gmail.com', NULL, '11111111111', 'Masculino', 'adminGP25', NOW(), 1),
  ('Médico', 'medico.GP25ads@gmail.com', NULL, '22222222222', 'Masculino', 'medicoGP2', NOW(), 2),
  ('Paciente', 'paciente.GP25ads@gmail.com', NULL, '33333333333', 'Feminino', 'pacientegp25', NOW(), 3);

-- Populando D_CLINICA
INSERT INTO D_CLINICA (CLINICA_NOME, CLINICA_DESC, CLINICA_TELEFONE, CLINICA_ESTADO, CLINICA_MUNICIPIO, CLINICA_BAIRRO, CLINICA_ENDERECO, CLINICA_NUMERO, CLINICA_CEP, CLINICA_END_COMPLEMENTO, CLINICA_DATA_CRIACAO)
VALUES
  ('Clinica A', 'Clinica de fisioterapia', '99999-9999', 'SP', 'São Paulo', 'Centro', 'Rua A', '123', '01000-000', 'Sala 1', NOW()),
  ('Clinica B', 'Clinica de ortopedia', '88888-8888', 'RJ', 'Rio de Janeiro', 'Copacabana', 'Rua B', '456', '22000-000', 'Sala 2', NOW());

-- Populando D_NOTIFICACAO
INSERT INTO D_NOTIFICACAO (NOTIFICACAO_TITULO, NOTIFICACAO_ASSUNTO, NOTIFICACAO_MENSAGEM, NOTIFICACAO_REMETENTE, NOTIFICACAO_DESTINATARIO, NOTIFICACAO_DATA_CRIACAO, F_USUARIO_ID)
VALUES
  ('Bem-vindo', 'Criação de Acesso', 'Seu acesso foi criado com sucesso.', 'admin@clinica.com', 'joao@teste.com', NOW(), 1),
  ('Atualização de Dados', 'Alteração de Cadastro', 'Seus dados foram atualizados.', 'admin@clinica.com', 'maria@teste.com', NOW(), 2);

-- Populando D_REABILITACAO
INSERT INTO D_REABILITACAO (REABILITACAO_NOME, REABILITACAO_DESC, REABILITACAO_MOMENTO, REABILITACAO_DESC_MOMENTO, REABILITACAO_ORDEM, REABILITACAO_DATA_CRIACAO)
VALUES
  ('Reabilitação A', 'Descrição A', 'Momento A', 'Descrição do Momento A', '1', NOW()),
  ('Reabilitação B', 'Descrição B', 'Momento B', 'Descrição do Momento B', '2', NOW());